### ISSUE TITLE
list layouts to use in yaml

### ISSUE THREAD

**Issue by juanpabloaj** [juanpabloaj/pypptx#1]
list layouts to use in yaml 

``` yaml
slides:
  - title: A title
    layout: 1
  - title: Other title
```

``` python
>>> for i, layout in enumerate(layouts):
...     print i, layout.name
0 Title Slide
1 Title and Content
2 Section Header
3 Two Content
4 Comparison
5 Title Only
6 Blank
7 Content with Caption
8 Picture with Caption
9 Title and Vertical Text
10 Vertical Title and Text
```
