### ISSUE TITLE
images with width, height and position

### ISSUE THREAD

**Issue by juanpabloaj** [juanpabloaj/pypptx#2]
``` yaml
slides:
  - title: Some title
    images:
      - name: image.jpg
        width: 200
        top: 2.4
      - name: image2.jpg
        ...
```
