### ISSUE TITLE
KeyError: 'no placeholder on this slide with idx == 1

### ISSUE THREAD

**Issue by juanpabloaj** [juanpabloaj/pypptx#5]
Get error with this yaml

``` yaml

    - title: slide
      text: some text
      layout: 6

```

``` yaml

    - title: slide
      text: some text
      layout: 5

```
